config/routes.rb
Rails.application.routes.draw do
  resources :people_us

end

app/models/people_u.rb
class PeopleU < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_us_controller.rb
class PeopleUsController < ApplicationController
  before_action :set_people_u, only: [:show, :edit, :update, :destroy]

  # GET /people_us
  # GET /people_us.json
  def index
    @people_us = PeopleU.all
  end

  # GET /people_us/1
  # GET /people_us/1.json
  def show
  end

  # GET /people_us/new
  def new
    @people_u = PeopleU.new
  end

  # GET /people_us/1/edit
  def edit
  end

  # POST /people_us
  # POST /people_us.json
  def create
    @people_u = PeopleU.new(people_u_params)

    respond_to do |format|
      if @people_u.save
        format.html { redirect_to @people_u, notice: 'People u was successfully created.' }
        format.json { render :show, status: :created, location: @people_u }
      else
        format.html { render :new }
        format.json { render json: @people_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people_us/1
  # PATCH/PUT /people_us/1.json
  def update
    respond_to do |format|
      if @people_u.update(people_u_params)
        format.html { redirect_to @people_u, notice: 'People u was successfully updated.' }
        format.json { render :show, status: :ok, location: @people_u }
      else
        format.html { render :edit }
        format.json { render json: @people_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people_us/1
  # DELETE /people_us/1.json
  def destroy
    @people_u.destroy
    respond_to do |format|
      format.html { redirect_to people_us_url, notice: 'People u was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_people_u
      @people_u = PeopleU.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def people_u_params
      params.require(:people_u).permit(:tableid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_us_helper.rb
module PeopleUsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPostgresTestProj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people_us/_form.html.erb
<%= form_for(@people_u) do |f| %>
  <% if @people_u.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@people_u.errors.count, "error") %> prohibited this people_u from being saved:</h2>

      <ul>
      <% @people_u.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tableid %><br>
    <%= f.text_field :tableid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people_us/edit.html.erb
<h1>Editing People U</h1>

<%= render 'form' %>

<%= link_to 'Show', @people_u %> |
<%= link_to 'Back', people_us_path %>

app/views/people_us/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People Us</h1>

<table>
  <thead>
    <tr>
      <th>Tableid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people_us.each do |people_u| %>
      <tr>
        <td><%= people_u.tableid %></td>
        <td><%= link_to 'Show', people_u %></td>
        <td><%= link_to 'Edit', edit_people_u_path(people_u) %></td>
        <td><%= link_to 'Destroy', people_u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New People u', new_people_u_path %>

app/views/people_us/new.html.erb
<h1>New People U</h1>

<%= render 'form' %>

<%= link_to 'Back', people_us_path %>

app/views/people_us/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tableid:</strong>
  <%= @people_u.tableid %>
</p>

<%= link_to 'Edit', edit_people_u_path(@people_u) %> |
<%= link_to 'Back', people_us_path %>